stages:
  - build-babylon
  - build-maid

build-babylon-arm64-v8a:
  stage: build-babylon
  image: registry.gitlab.com/fdroid/fdroidserver:buildserver-bookworm
  tags:
    - saas-linux-medium-amd64
  only:
    - main
  variables:
    ANDROID_NDK_HOME: /opt/android-ndk
  before_script:
    - apt-get update
    - apt-get install -y cmake make unzip git wget
    - wget https://dl.google.com/android/repository/android-ndk-r27-linux.zip
    - unzip android-ndk-r27-linux.zip -d /opt
    - export ANDROID_NDK_HOME=/opt/android-ndk-r27
    - echo "ANDROID_NDK_HOME=${ANDROID_NDK_HOME}" >> /etc/environment
    - git clone --recursive https://github.com/Mobile-Artificial-Intelligence/babylon.cpp
  script:
    - export ANDROID_NDK_HOME=/opt/android-ndk-r27
    - cd babylon.cpp
    - mkdir -p build/arm64-v8a
    - cmake -B build/arm64-v8a -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21
    - cmake --build build/arm64-v8a --config Release -- -j$(nproc)
  artifacts:
    paths:
      - babylon.cpp/build/arm64-v8a/lib/

build-babylon-x86_64:
  stage: build-babylon
  image: registry.gitlab.com/fdroid/fdroidserver:buildserver-bookworm
  tags:
    - saas-linux-medium-amd64
  only:
    - main
  variables:
    ANDROID_NDK_HOME: /opt/android-ndk
  before_script:
    - apt-get update
    - apt-get install -y cmake unzip git
    - wget https://dl.google.com/android/repository/android-ndk-r27-linux.zip
    - unzip android-ndk-r27-linux.zip -d /opt
    - export ANDROID_NDK_HOME=/opt/android-ndk-r27
    - echo "ANDROID_NDK_HOME=${ANDROID_NDK_HOME}" >> /etc/environment
    - git clone https://github.com/Mobile-Artificial-Intelligence/babylon.cpp
  script:
    - export ANDROID_NDK_HOME=/opt/android-ndk-r27
    - cd babylon.cpp
    - mkdir -p build/x86_64
    - cmake -B build/x86_64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake -DANDROID_ABI=x86_64 -DANDROID_PLATFORM=android-21
    - cmake --build build/x86_64 --config Release -- -j$(nproc)
  artifacts:
    paths:
      - babylon.cpp/build/x86_64/lib/

build-maid:
  stage: build-maid
  image: registry.gitlab.com/fdroid/fdroidserver:buildserver-bookworm
  tags:
    - saas-linux-medium-amd64
  only:
    - main
  dependencies:
    - build-babylon-arm64-v8a
    - build-babylon-x86_64
  variables:
    repo: /home/runner/work/maid
    ANDROID_HOME: /opt/android-sdk
    ANDROID_SDK_ROOT: ${ANDROID_HOME}
  before_script:
    - rm -rf /home/vagrant/build
    - rm -rf /opt/android-sdk/ndk
    - apt-get update 
    - apt-get install -y openjdk-17-jdk-headless
    - rm -rf $ANDROID_HOME/tools
    - sdkmanager "tools" "platform-tools" "build-tools;31.0.0"
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - rm -rf ./packages/babylon_tts/android/app/src/main/jniLibs
    - mkdir -p ./packages/babylon_tts/android/app/src/main/jniLibs/arm64-v8a
    - mkdir -p ./packages/babylon_tts/android/app/src/main/jniLibs/x86_64
  script:
    - export PUB_CACHE=$(pwd)/.pub-cache
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    - cp babylon.cpp/build/arm64-v8a/lib/* ./packages/babylon_tts/android/app/src/main/jniLibs/arm64-v8a/
    - cp babylon.cpp/build/x86_64/lib/* ./packages/babylon_tts/android/app/src/main/jniLibs/x86_64/

    # Build and configure Flutter from submodule
    - ./packages/flutter/bin/flutter config --no-analytics
    - ./packages/flutter/bin/flutter packages pub get

    # Decrypt the keystore
    - echo "$KEYSTORE" | base64 --decode > ./android/app/key.jks
    - |
      echo "storeFile=key.jks" > ./android/key.properties
      echo "storePassword=$STORE_PASSWORD" >> ./android/key.properties
      echo "releasePassword=$KEY_PASSWORD" >> ./android/key.properties
      echo "releaseAlias=$KEY_ALIAS" >> ./android/key.properties

    # Build the APKs split by ABI
    - ./packages/flutter/bin/flutter build apk --split-per-abi

    # Rename the APKs
    - mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/maid-android-arm64-v8a.apk
    - mv build/app/outputs/flutter-apk/app-x86_64-release.apk build/app/outputs/flutter-apk/maid-android-x86_64.apk
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/maid-android-arm64-v8a.apk
      - build/app/outputs/flutter-apk/maid-android-x86_64.apk
