name: Build macOS

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Set up signing certificates
        run: |
          echo "${{ secrets.APPLE_CERTIFICATE }}" | base64 --decode > macos_certificate.p12
          security create-keychain -p ${{ secrets.APPLE_PASSWORD }} temp.keychain
          security import macos_certificate.p12 -k temp.keychain -P ${{ secrets.APPLE_PASSWORD }} -T /usr/bin/codesign
          security list-keychains -s temp.keychain
          security unlock-keychain -p ${{ secrets.APPLE_PASSWORD }} temp.keychain
          security set-keychain-settings -lut 7200 temp.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k ${{ secrets.APPLE_PASSWORD }} temp.keychain
          mkdir -p ~/Library/Developer/Xcode/Provisioning\ Profiles
          echo "${{ secrets.APPLE_PROVISION_PROFILE }}" | base64 --decode > ~/Library/Developer/Xcode/Provisioning\ Profiles/Github_Actions.provisionprofile

      - name: Build macOS App
        run: |
          flutter pub get
          flutter build macos

      - name: Move .app to Separate Directory
        run: |
          mkdir -p build/macos/Build/Products/Release/Upload
          mv build/macos/Build/Products/Release/maid.app build/macos/Build/Products/Release/Upload/

      - name: Sign macOS App
        run: |
          codesign --deep --force --verbose --sign "${{ secrets.APPLE_DEVELOPER_ID_APPLICATION }}" build/macos/Build/Products/Release/Upload/maid.app

      - name: Ensure Executable Permissions
        run: |
          chmod +x build/macos/Build/Products/Release/Upload/maid.app/Contents/MacOS/*

      - name: Notarize macOS App
        run: |
          xcrun altool --notarize-app --primary-bundle-id "com.danemadsen.maid" --username "${{ secrets.APPLE_ID }}" --password "${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}" --file build/macos/Build/Products/Release/Upload/maid.app --output-format xml > notarization_output.xml
          cat notarization_output.xml
          REQUEST_UUID=$(xmllint --xpath 'string(//notarization-upload/request-id)' notarization_output.xml)
          echo "Request UUID: $REQUEST_UUID"

      - name: Check Notarization Status
        run: |
          attempts=0
          while true; do
            echo "Checking notarization status (attempt $attempts)..."
            xcrun altool --notarization-info $REQUEST_UUID --username "${{ secrets.APPLE_ID }}" --password "${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}" --output-format xml > notarization_status.xml
            cat notarization_status.xml
            NOTARIZATION_STATUS=$(xmllint --xpath 'string(//notarization-info/status)' notarization_status.xml)
            if [ "$NOTARIZATION_STATUS" = "success" ]; then
              echo "Notarization succeeded"
              break
            elif [ "$NOTARIZATION_STATUS" = "in progress" ]; then
              echo "Notarization in progress, waiting..."
              sleep 60  # Wait before checking again
              attempts=$((attempts + 1))
              if [ $attempts -ge 30 ]; then  # Timeout after 30 minutes
                echo "Notarization timed out"
                exit 1
              fi
            else
              echo "Notarization failed"
              exit 1
            fi
          done

      - name: Staple Notarization Ticket
        run: |
          xcrun stapler staple build/macos/Build/Products/Release/Upload/maid.app

      - name: Verify Code Signature
        run: |
          codesign --verify --deep --verbose build/macos/Build/Products/Release/Upload/maid.app
          spctl --assess --type execute --verbose=4 build/macos/Build/Products/Release/Upload/maid.app

      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: maid-macos-${{ matrix.arch }}
          path: build/macos/Build/Products/Release/Upload
