name: Build macOS

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE }}
          p12-password: ${{ secrets.APPLE_PASSWORD }}

      - name: Install the provisioning profile
        run: |
          mkdir -p ~/Library/Developer/Xcode/Provisioning\ Profiles
          echo "${{ secrets.APPLE_PROVISION_PROFILE }}" | base64 --decode > ~/Library/Developer/Xcode/Provisioning\ Profiles/Github_Actions.provisionprofile

      - name: Build macOS App
        run: |
          flutter pub get
          flutter build macos

      - name: Sign macOS App
        run: |
          codesign --deep --force --verbose --options runtime --timestamp --sign "${{ secrets.APPLE_DEVELOPER_ID_APPLICATION }}" build/macos/Build/Products/Release/maid.app

          find build/macos/Build/Products/Release/maid.app -type d -name "*.framework" -exec codesign --force --verbose --options runtime --timestamp --sign "${{ secrets.APPLE_DEVELOPER_ID_APPLICATION }}" {} \;
          find build/macos/Build/Products/Release/maid.app -type f -exec codesign --force --verbose --options runtime --timestamp --sign "${{ secrets.APPLE_DEVELOPER_ID_APPLICATION }}" {} \;

          codesign --verify --deep --strict --verbose build/macos/Build/Products/Release/maid.app

      - name: Create DMG
        run: |
          mkdir -p dmg
          mkdir -p /Volumes/Maid

          # Create temporary DMG
          hdiutil create dmg/maid_tmp.dmg -volname "Maid" -srcfolder build/macos/Build/Products/Release/maid.app -ov -format UDRW

          # Mount the temporary DMG
          hdiutil attach dmg/maid_tmp.dmg -mountpoint /Volumes/Maid

          # Copy background image
          mkdir /Volumes/Maid/.background
          cp ./media/feature.png /Volumes/Maid/.background/feature.png

          # Create a symbolic link to the Applications folder
          ln -s /Applications /Volumes/Maid/Applications

          # Set the background image
          echo '
          tell application "Finder"
            tell disk "Maid"
              open
              set current view of container window to icon view
              set toolbar visible of container window to false
              set statusbar visible of container window to false
              set the bounds of container window to {0, 0, 1024, 500}
              set viewOptions to the icon view options of container window
              set arrangement of viewOptions to not arranged
              set icon size of viewOptions to 128
              set background picture of viewOptions to file ".background:feature.png"
              set position of item "maid.app" of container window to {200, 300}
              set position of item "Applications" of container window to {800, 300}
              close
              open
              update without registering applications
              delay 5
            end tell
          end tell
          ' | osascript

          # Unmount the temporary DMG
          hdiutil detach /Volumes/Maid

          # Convert to final DMG
          hdiutil convert dmg/maid_tmp.dmg -format UDZO -o dmg/maid.dmg

          # Remove temporary DMG
          rm dmg/maid_tmp.dmg

      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: maid-macos-${{ matrix.arch }}
          path: dmg
