name: Build macOS

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
        
      - name: Install dependencies
        run: |
          brew install cmake ninja

      - name: Set up signing certificates
        run: |
          echo "${{ secrets.APPLE_CERTIFICATE }}" | base64 --decode > macos_certificate.p12
          security create-keychain -p ${{ secrets.APPLE_PASSWORD }} build.keychain
          security import macos_certificate.p12 -k ~/Library/Keychains/build.keychain -P ${{ secrets.APPLE_PASSWORD }} -T /usr/bin/codesign
          security list-keychains -d user -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p ${{ secrets.APPLE_PASSWORD }} ~/Library/Keychains/build.keychain
          security set-keychain-settings -lut 7200 ~/Library/Keychains/build.keychain
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.APPLE_PROVISION_PROFILE }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/macos_provisioning.mobileprovision

      - name: Build macOS App
        run: |
          flutter pub get
          flutter build macos

      - name: Sign macOS App
        run: |
          codesign --deep --force --verbose --sign ${{ secrets.APPLE_DEVELOPER_ID_APPLICATION }} build/macos/Build/Products/Release/maid.app

      - name: Set execute permissions
        run: |
          chmod +x build/macos/Build/Products/Release/maid.app

      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: maid-macos-${{ matrix.arch }}
          path: build/macos/Build/Products/Release/maid.app
