name: Build macOS

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE }}
          p12-password: ${{ secrets.APPLE_PASSWORD }}

      - name: Install the provisioning profile
        run: |
          mkdir -p ~/Library/Developer/Xcode/Provisioning\ Profiles
          echo "${{ secrets.APPLE_PROVISION_PROFILE }}" | base64 --decode > ~/Library/Developer/Xcode/Provisioning\ Profiles/Github_Actions.provisionprofile

      - name: Build macOS App
        run: |
          flutter pub get
          flutter build macos

      - name: Move .app to Separate Directory
        run: |
          mkdir -p build/macos/Build/Products/Release/Upload
          mv build/macos/Build/Products/Release/maid.app build/macos/Build/Products/Release/Upload/

      - name: Sign macOS App
        run: |
          codesign --deep --force --verbose --options runtime --timestamp --sign "${{ secrets.APPLE_DEVELOPER_ID_APPLICATION }}" build/macos/Build/Products/Release/Upload/maid.app

          find build/macos/Build/Products/Release/Upload/maid.app -type d -name "*.framework" -exec codesign --force --verbose --options runtime --timestamp --sign "${{ secrets.APPLE_DEVELOPER_ID_APPLICATION }}" {} \;
          find build/macos/Build/Products/Release/Upload/maid.app -type f -exec codesign --force --verbose --options runtime --timestamp --sign "${{ secrets.APPLE_DEVELOPER_ID_APPLICATION }}" {} \;

          codesign --verify --deep --strict --verbose build/macos/Build/Products/Release/Upload/maid.app

      - name: Create DMG
        run: |
          mkdir -p dmg
          hdiutil create dmg/maid.dmg -srcfolder build/macos/Build/Products/Release/Upload/maid.app -ov -format UDZO

      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: maid-macos-${{ matrix.arch }}
          path: dmg
